/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FireCore;

import static FireCore.IpConnection.smtpSocket;
import static FireCore.IpConnection.writeData;
import static FireCore.SqlSiteSetUp.host;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.Timer;

import javax.swing.tree.DefaultTreeCellRenderer;


/**
 *
 * @author TANDE
 */
public class PanelSetUpPage extends javax.swing.JFrame {

    private static String bldNameInput = null;
    private static int sidNumInput;
    private static int sidNumInputString;
    private static int portNumInput;
    private static String ipAddress;
    private static String manufacturer;
    private static final String ipAddressPattern = "^([01]?\\d\\d?|2[0-4]\\d|[0-5])\\." + "([01]?\\d\\d?|2[0-4]\\d|[0-5])\\." + "([01]?\\d\\d?|2[0-4]\\d|[0-5])\\." + "([01]?\\d\\d?|2[0-4]\\d|[0-5])$";
    private Pattern pattern;
    private Matcher matcher;
    private Enumeration ports = null;

    private static void GetPanelInfo() {

        bldNameInput = bldNamFeild.getText();
        sidNumInput =  Integer.parseInt(selectSidNum.getText());
       ipAddress = ipAddressInput.getText();
       portNumInput = Integer.parseInt(PorttNumInput.getText());
       manufacturer = fipBrandSelection.getSelectedItem().toString();

            SqlUpdateSiteInfo.SqlUpdateSiteInfo(bldNameInput,sidNumInput,ipAddress,portNumInput, manufacturer);

       

    }

    private void PanelConnect() throws IOException, SQLException {

        pattern = Pattern.compile(ipAddressPattern);
        ipAddress = ipAddressInput.getText();
        matcher = pattern.matcher(ipAddress);

        System.out.println(matcher.matches());

        portNumInput = Integer.parseInt(PorttNumInput.getText());

        IpConnection.IpConnect(portNumInput, ipAddress);
        
     

    }

    /**
     * Creates new form PanelSetUpPage
     */
    public PanelSetUpPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelNumLab = new javax.swing.JLabel();
        bldNameLab = new javax.swing.JLabel();
        panelNumDisplay = new javax.swing.JLabel();
        mainSiteNamelab = new javax.swing.JLabel();
        sidNumLab = new javax.swing.JLabel();
        bldNamFeild = new javax.swing.JTextField();
        mainSiteNameInput = new javax.swing.JLabel();
        selectSidNum = new javax.swing.JTextField();
        fipBrandSelection = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        PorttNumInput = new javax.swing.JTextField();
        ipAddressInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonPanelConnect = new javax.swing.JButton();
        panelDisconect = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        savePanelInfo = new javax.swing.JMenuItem();
        exitPanelSetUpPage = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        panelNumLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelNumLab.setText("Panel Number:");

        bldNameLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bldNameLab.setText("Building Name:");

        mainSiteNamelab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mainSiteNamelab.setText("Main Site Name:");

        sidNumLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sidNumLab.setText("SID Number:");

        mainSiteNameInput.setText("jLabel3");

        fipBrandSelection.setToolTipText("");

        jLabel3.setText("Select Panel Manufacturer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bldNameLab)
                            .addComponent(mainSiteNamelab)
                            .addComponent(bldNamFeild, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(mainSiteNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(sidNumLab)
                                    .addGap(72, 72, 72))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(selectSidNum, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(81, 81, 81))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(panelNumLab)
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(panelNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(fipBrandSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainSiteNamelab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNumLab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainSiteNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bldNameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidNumLab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bldNamFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectSidNum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fipBrandSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Network"));

        jLabel1.setText("Port Num:");

        jLabel2.setText("IP Address:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PorttNumInput, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(ipAddressInput, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PorttNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26))
        );

        jButtonPanelConnect.setText("Connect");
        jButtonPanelConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPanelConnectActionPerformed(evt);
            }
        });

        panelDisconect.setText("Disconnect");
        panelDisconect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelDisconectActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        savePanelInfo.setText("Save ");
        savePanelInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePanelInfoActionPerformed(evt);
            }
        });
        jMenu1.add(savePanelInfo);

        exitPanelSetUpPage.setText("Exit");
        exitPanelSetUpPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitPanelSetUpPageActionPerformed(evt);
            }
        });
        jMenu1.add(exitPanelSetUpPage);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonPanelConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDisconect, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panelDisconect, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPanelConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPanelConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPanelConnectActionPerformed
      
        try {
            try {
                PanelConnect();
            } catch (SQLException ex) {
                Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }
       
      
        dispose();
        
        try {
            IpConnection.writeData();
        } catch (IOException ex) {
            Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        
       
        
 
    }//GEN-LAST:event_jButtonPanelConnectActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
            dispose();

    }//GEN-LAST:event_formWindowClosing

    private void panelDisconectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelDisconectActionPerformed
      
        try {
            IpConnection.closeConnections();
        } catch (IOException ex) {
            Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_panelDisconectActionPerformed

    private void savePanelInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePanelInfoActionPerformed
         
       
        GetPanelInfo();
    }//GEN-LAST:event_savePanelInfoActionPerformed

    private void exitPanelSetUpPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitPanelSetUpPageActionPerformed
        dispose();
    }//GEN-LAST:event_exitPanelSetUpPageActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
        Connection con = null;
        try {
            con = DriverManager.getConnection(host);
        } catch (SQLException ex) {
            Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }
            System.out.println("Connected");
            String query = "SELECT * FROM db_accessadmin.Fire_Panel_Brands";
            Statement st = null;
        try {
            st = con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            ResultSet rs = st.executeQuery(query);
             while (rs.next()) {
        
        String panelBrand = rs.getString("ManufacturerName");
        
                fipBrandSelection.addItem(panelBrand);
        
        }
        } catch (SQLException ex) {
            Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelSetUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelSetUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelSetUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSetUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelSetUpPage().setVisible(true);
                 
            }

   
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField PorttNumInput;
    public static javax.swing.JTextField bldNamFeild;
    private javax.swing.JLabel bldNameLab;
    private javax.swing.JMenuItem exitPanelSetUpPage;
    private static javax.swing.JComboBox<String> fipBrandSelection;
    public static javax.swing.JTextField ipAddressInput;
    private javax.swing.JButton jButtonPanelConnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel mainSiteNameInput;
    private javax.swing.JLabel mainSiteNamelab;
    private javax.swing.JButton panelDisconect;
    public static javax.swing.JLabel panelNumDisplay;
    private javax.swing.JLabel panelNumLab;
    private javax.swing.JMenuItem savePanelInfo;
    public static javax.swing.JTextField selectSidNum;
    private javax.swing.JLabel sidNumLab;
    // End of variables declaration//GEN-END:variables

}
