/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FireCore;

import static FireCore.IpConnection.smtpSocket;
import static FireCore.IpConnection.writeData;
import static FireCore.SqlFunctions.host;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author TANDE
 */
public class PanelSetUpPage extends javax.swing.JFrame {

    private static String bldNameInput = null;
    private static int sidNumInput;
    public static int portNumInput;
    private static int panelID;
    public static String ipAddress;
    private static String manufacturer;
    private static final String ipAddressPattern = "^([01]?\\d\\d?|2[0-4]\\d|[0-5])\\." + "([01]?\\d\\d?|2[0-4]\\d|[0-5])\\." + "([01]?\\d\\d?|2[0-4]\\d|[0-5])\\." + "([01]?\\d\\d?|2[0-4]\\d|[0-5])$";
    private Pattern pattern;
    private Matcher matcher;
    private Enumeration ports = null;

    private static void GetPanelInfo() {

        bldNameInput = bldNamFeild.getText();
        sidNumInput = Integer.parseInt(selectSidNum.getText());
        ipAddress = ipAddressInput.getText();
        portNumInput = Integer.parseInt(PortNumInput.getText());
        manufacturer = fipBrandSelection.getSelectedItem().toString();

        SqlFunctions.SqlUpdateSiteInfo(bldNameInput, sidNumInput, ipAddress, portNumInput, manufacturer);

    }

    private void PanelConnect() throws IOException, SQLException {

        pattern = Pattern.compile(ipAddressPattern);
        ipAddress = ipAddressInput.getText();
        matcher = pattern.matcher(ipAddress);

        System.out.println(matcher.matches());

        portNumInput = Integer.parseInt(PortNumInput.getText());
        panelID = Integer.parseInt(panelNumDisplay.getText());

        SqlFunctions.CheckIpAndPanId(ipAddress, panelID, portNumInput);

    }

    /**
     * Creates new form PanelSetUpPage
     */
    public PanelSetUpPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelNumLab = new javax.swing.JLabel();
        bldNameLab = new javax.swing.JLabel();
        panelNumDisplay = new javax.swing.JLabel();
        mainSiteNamelab = new javax.swing.JLabel();
        sidNumLab = new javax.swing.JLabel();
        bldNamFeild = new javax.swing.JTextField();
        mainSiteNameInput = new javax.swing.JLabel();
        selectSidNum = new javax.swing.JTextField();
        fipBrandSelection = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButtonPanelConnect = new javax.swing.JButton();
        panelDisconect = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        mx1Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PortNumInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ipAddressInput = new javax.swing.JTextField();
        ampacPanel = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        panel1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        editFields = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        savePanelInfo = new javax.swing.JMenuItem();
        exitPanelSetUpPage = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        panelNumLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelNumLab.setText("Panel Number:");

        bldNameLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bldNameLab.setText("Building Name:");

        mainSiteNamelab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mainSiteNamelab.setText("Main Site Name:");

        sidNumLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sidNumLab.setText("SID Number:");

        fipBrandSelection.setToolTipText("");

        jLabel3.setText("Select Panel Manufacturer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bldNameLab)
                                    .addComponent(mainSiteNamelab)
                                    .addComponent(bldNamFeild, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(mainSiteNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(126, 126, 126)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelNumLab)
                                    .addComponent(selectSidNum, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(panelNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sidNumLab))))
                            .addComponent(fipBrandSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainSiteNamelab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNumLab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainSiteNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bldNameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidNumLab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bldNamFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectSidNum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fipBrandSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButtonPanelConnect.setText("Connect");
        jButtonPanelConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPanelConnectActionPerformed(evt);
            }
        });

        panelDisconect.setText("Disconnect");
        panelDisconect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelDisconectActionPerformed(evt);
            }
        });

        mx1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("MX1 Network"));

        jLabel1.setText("Port Number:");

        PortNumInput.setText("jTextField1");

        jLabel2.setText("IP Address:");

        ipAddressInput.setText("jTextField2");

        javax.swing.GroupLayout mx1PanelLayout = new javax.swing.GroupLayout(mx1Panel);
        mx1Panel.setLayout(mx1PanelLayout);
        mx1PanelLayout.setHorizontalGroup(
            mx1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mx1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mx1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(mx1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ipAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PortNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mx1PanelLayout.setVerticalGroup(
            mx1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mx1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mx1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PortNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(mx1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ipAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ampacPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ampac Network"));

        jLabel4.setText("FUCK YOU");

        ampacPanel.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ampacPanelLayout = new javax.swing.GroupLayout(ampacPanel);
        ampacPanel.setLayout(ampacPanelLayout);
        ampacPanelLayout.setHorizontalGroup(
            ampacPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ampacPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        ampacPanelLayout.setVerticalGroup(
            ampacPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ampacPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(mx1Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ampacPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mx1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(ampacPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mx1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ampacPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(203, Short.MAX_VALUE)))
        );

        panel1.setText("Panel 1");
        panel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panel1ActionPerformed(evt);
            }
        });

        jButton1.setText("Panel 2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        editFields.setText("Edit Fields");
        editFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFieldsActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        savePanelInfo.setText("Save ");
        savePanelInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePanelInfoActionPerformed(evt);
            }
        });
        jMenu1.add(savePanelInfo);

        exitPanelSetUpPage.setText("Exit");
        exitPanelSetUpPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitPanelSetUpPageActionPerformed(evt);
            }
        });
        jMenu1.add(exitPanelSetUpPage);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1)
                        .addGap(50, 50, 50)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLayeredPane1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editFields, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPanelConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelDisconect)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panel1)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPanelConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDisconect, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editFields, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPanelConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPanelConnectActionPerformed

        try {
            try {
                PanelConnect();
            } catch (SQLException ex) {
                Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();

        try {
            IpConnection.writeData();
        } catch (IOException ex) {
            Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonPanelConnectActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        dispose();

    }//GEN-LAST:event_formWindowClosing

    private void panelDisconectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelDisconectActionPerformed

        try {
            IpConnection.closeConnections();
        } catch (IOException ex) {
            Logger.getLogger(PanelSetUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_panelDisconectActionPerformed

    private void savePanelInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePanelInfoActionPerformed

        GetPanelInfo();
        
    }//GEN-LAST:event_savePanelInfoActionPerformed

    private void exitPanelSetUpPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitPanelSetUpPageActionPerformed
        dispose();
    }//GEN-LAST:event_exitPanelSetUpPageActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

       
       PortNumInput.setEnabled(false);
       ipAddressInput.setEnabled(false);
       fipBrandSelection.setEnabled(false);


    }//GEN-LAST:event_formWindowOpened

    private void panel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panel1ActionPerformed
       mx1Panel.setVisible(true);
       ampacPanel.setVisible(false);
    }//GEN-LAST:event_panel1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          mx1Panel.setVisible(false);
       ampacPanel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFieldsActionPerformed
        PortNumInput.setEnabled(true);
        ipAddressInput.setEnabled(true);
       fipBrandSelection.setEnabled(true);
    }//GEN-LAST:event_editFieldsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelSetUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelSetUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelSetUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSetUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelSetUpPage().setVisible(true);

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField PortNumInput;
    public static javax.swing.JLayeredPane ampacPanel;
    public static javax.swing.JTextField bldNamFeild;
    private javax.swing.JLabel bldNameLab;
    private javax.swing.JButton editFields;
    private javax.swing.JMenuItem exitPanelSetUpPage;
    public static javax.swing.JComboBox<String> fipBrandSelection;
    public static javax.swing.JTextField ipAddressInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPanelConnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel mainSiteNameInput;
    private javax.swing.JLabel mainSiteNamelab;
    public static javax.swing.JPanel mx1Panel;
    private javax.swing.JButton panel1;
    private javax.swing.JButton panelDisconect;
    public static javax.swing.JLabel panelNumDisplay;
    private javax.swing.JLabel panelNumLab;
    private javax.swing.JMenuItem savePanelInfo;
    public static javax.swing.JTextField selectSidNum;
    private javax.swing.JLabel sidNumLab;
    // End of variables declaration//GEN-END:variables

}
